version: "3.5"

services:
  go:
    container_name: babycrab-go-local
    image: golang:1.17
    ports:
      - "8080:8080"    
    environment:
      APP_ENV: dev
      DATABASE_URL: postgres://babycrab:babycrab@db:5432/babycrab?sslmode=disable
    volumes:
      - .:/babycrab:cached
      - babycrab-go-build-cache:/root/.cache/go-build
  db:
    container_name: babycrab-db-local
    image: postgres:12-alpine
    ports:
      - "5432:5432"    
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: babycrab
      POSTGRES_HOST_AUTH_METHOD: trust
  db-migrate:
    container_name: babycrab-db-migrate-local
    image: migrate/migrate:v4.14.1
    depends_on:
      - db
    volumes:
      - migration-files:/migrations    
    restart: "no"
    entrypoint: ""
    environment:
      DATABASE_URL: postgres://babycrab:@db:5432/babycrab?sslmode=disable
 
volumes:
  babycrab-go-build-cache:
    name: babycrab-go-build-cache-dev
  migration-files:
    name: babycrab-migrate-local
