// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Friends          string
	SchemaMigrations string
	Subscriptions    string
	UserBlocks       string
	Users            string
}{
	Friends:          "friends",
	SchemaMigrations: "schema_migrations",
	Subscriptions:    "subscriptions",
	UserBlocks:       "user_blocks",
	Users:            "users",
}
