// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Friends", testFriendsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Subscriptions", testSubscriptionsUpsert)

	t.Run("UserBlocks", testUserBlocksUpsert)

	t.Run("Users", testUsersUpsert)
}
